### ISSUE TITLE
Improve taglines

### ISSUE THREAD

**Issue by brillout** [brillout/awesome-react-frameworks#1]
I copy-pasted the taglines from the frameworks' websites/GitHub.

But some of them, most notably Next.js's `The React Framework` doesn't make much sense in this context.

In the long term it's best the framework authors decide their taglines for this list. In the meantime and for frameworks that don't care about this list, we should improve the taglines on their behalf. E.g. how about we replace Next.js's `The React Framework` with `The first and most popular React framework`?

**Comment by redbar0n** [comment]
Yeah, I think it's best to just keep them as they are, without doing anything on anyones behalf (for not being accused of bias), but instead add quotation marks, so that people know it's their own words.

**Comment by brillout** [comment]
Good point & idea.

**Comment by redbar0n** [comment]
Done :)
